/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CheckpointRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getLatestCheckpoint" | "hasCheckpoint" | "saveCheckpoint"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CheckpointSaved" | "CheckpointUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getLatestCheckpoint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCheckpoint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "saveCheckpoint",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLatestCheckpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCheckpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "saveCheckpoint",
    data: BytesLike
  ): Result;
}

export namespace CheckpointSavedEvent {
  export type InputTuple = [
    agentId: string,
    rootHash: string,
    timestamp: BigNumberish,
    savedBy: AddressLike
  ];
  export type OutputTuple = [
    agentId: string,
    rootHash: string,
    timestamp: bigint,
    savedBy: string
  ];
  export interface OutputObject {
    agentId: string;
    rootHash: string;
    timestamp: bigint;
    savedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CheckpointUpdatedEvent {
  export type InputTuple = [
    agentId: string,
    oldRootHash: string,
    newRootHash: string,
    timestamp: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    agentId: string,
    oldRootHash: string,
    newRootHash: string,
    timestamp: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    agentId: string;
    oldRootHash: string;
    newRootHash: string;
    timestamp: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CheckpointRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CheckpointRegistry;
  waitForDeployment(): Promise<this>;

  interface: CheckpointRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLatestCheckpoint: TypedContractMethod<[agentId: string], [string], "view">;

  hasCheckpoint: TypedContractMethod<[agentId: string], [boolean], "view">;

  saveCheckpoint: TypedContractMethod<
    [agentId: string, rootHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLatestCheckpoint"
  ): TypedContractMethod<[agentId: string], [string], "view">;
  getFunction(
    nameOrSignature: "hasCheckpoint"
  ): TypedContractMethod<[agentId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "saveCheckpoint"
  ): TypedContractMethod<
    [agentId: string, rootHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CheckpointSaved"
  ): TypedContractEvent<
    CheckpointSavedEvent.InputTuple,
    CheckpointSavedEvent.OutputTuple,
    CheckpointSavedEvent.OutputObject
  >;
  getEvent(
    key: "CheckpointUpdated"
  ): TypedContractEvent<
    CheckpointUpdatedEvent.InputTuple,
    CheckpointUpdatedEvent.OutputTuple,
    CheckpointUpdatedEvent.OutputObject
  >;

  filters: {
    "CheckpointSaved(string,string,uint256,address)": TypedContractEvent<
      CheckpointSavedEvent.InputTuple,
      CheckpointSavedEvent.OutputTuple,
      CheckpointSavedEvent.OutputObject
    >;
    CheckpointSaved: TypedContractEvent<
      CheckpointSavedEvent.InputTuple,
      CheckpointSavedEvent.OutputTuple,
      CheckpointSavedEvent.OutputObject
    >;

    "CheckpointUpdated(string,string,string,uint256,address)": TypedContractEvent<
      CheckpointUpdatedEvent.InputTuple,
      CheckpointUpdatedEvent.OutputTuple,
      CheckpointUpdatedEvent.OutputObject
    >;
    CheckpointUpdated: TypedContractEvent<
      CheckpointUpdatedEvent.InputTuple,
      CheckpointUpdatedEvent.OutputTuple,
      CheckpointUpdatedEvent.OutputObject
    >;
  };
}
